### ISSUE TITLE
[UI issue]Footer Navigation Links Mismatch

### ISSUE THREAD

**Issue by opfocus** [ethereum-optimism/docs#1133]
I noticed an issue with the footer navigation links on the documentation site. The links for "Previous" and "Next" pages appear to be incorrectly labeled:

- The "Previous" page link actually points to the current page instead of the actual previous page.
- The "Next" page link seems to be pointing to the page after the next, instead of the immediate next page.

This is causing confusion for users navigating through the documentation. Please see the attached screenshot for clarification.
![Image](https://github.com/user-attachments/assets/92f3ec4f-3ec0-44f8-a358-6196943ddcb5)

**Comment by krofax** [comment]
@opfocus Thanks for spotting this, we will prfioritize it.

**Comment by krofax** [comment]
@opfocus We turned this off temporarily, until we have enough bandwidth to fix this. Thanks for spotting this again.
