### ISSUE TITLE
[DOCS] Superchain Interop Explainer 404

### ISSUE THREAD

**Issue by parseb** [ethereum-optimism/docs#1165]
## Brief Description of the Docs Request
Last link on [deploy-superchain-erc20](https://docs.optimism.io/stack/interop/assets/deploy-superchain-erc20) 404s. The _Superchain Interop Explainer_ is missing.

## Description of the Documentation You'd Like
Page is missing or the link is bad.

## Links to Related Pages

* https://docs.optimism.io/stack/interop/assets/deploy-superchain-erc20 (source)
* https://docs.optimism.io/stack/interop/assets/explainer (404)

**Comment by krofax** [comment]
Fixed the issue with this [PR](https://github.com/ethereum-optimism/docs/pull/1166)
