### ISSUE TITLE
[FEEDBACK] Bridging Domains Part A

### ISSUE THREAD

**Issue by opfocus** [ethereum-optimism/docs#119]
Location: https://docs.optimism.io/dapp-developers/bridging/messaging
1. Quotation: inside of the Optimism monorepo
lost link

2. Quotation: happen to the State Commitment Chain (on both mainnet and goerli).
maybe a wrong description and link

3. Quotation: a call to the CanonicalTransactionChain
lost link (The develop branch ofoptimism does not contain the path )

4. Quotation: To see the present values, go to Etherscan
need check(maybe a wrong link)

5. Quotation: it includes verifying a Merkle trie 
need check (Unexpected link)

Location: https://docs.optimism.io/dapp-developers/bridging/standard-bridge-custom-token
1. Quotation: new IOptimismMintableERC20 interface.
lost link

2. Quotation: l1Factory = await ethers.getContractFactory("OptimismUselessToken")
OptimismUselessToken(Contract text is missing)

Location: https://docs.optimism.io/dapp-developers/bridging/cross-dom-bridge-eth
Quotation: Hop
lost link

Quotation: Synapse
lost link

Quotation: Across
lost link

Location: https://docs.optimism.io/dapp-developers/bridging/cross-dom-solidity
1. Quotation: address of Proxy_OVM_L1CrossDomainMessenger 
Outdated names and links

2. Quotation: you need to use this address. 
Outdated names and links

Location: https://docs.optimism.io/dapp-developers/bridging/cross-dom-solidity
The L2 to L1 process is missing, and no explanation has been provided.

**Additionally：**
The installation package has not been updated to the latest version, and I'm unsure if this is something to be concerned about. 
Also, I would like to know the team's stance on the @eth-optimism/contracts package—whether it is recommended to continue using it or if there are plans for it to be replaced by another installation package.

**Comment by cpengilly** [comment]
@opfocus can you clarify which docs page you are addressing with this comment? 
The installation package has not been updated to the latest version, and I'm unsure if this is something to be concerned about.

**Comment by opfocus** [comment]
e.g：  https://docs.optimism.io/dapp-developers/bridging/standard-bridge-standard-token

pnpm add @eth-optimism/sdk@^3.0.0 dotenv@^10.0.0 @eth-optimism/contracts@^0.5.40 @openzeppelin/contracts^4.3.2

can be replaced by：
```
pnpm add @eth-optimism/sdk dotenv @openzeppelin/contracts
```


The changes specified in the following text need to be made
```
# Before replacement
fname = "node_modules/@eth-optimism/contracts-bedrock/artifacts/contracts/universal/OptimismMintableERC20Factory.sol/OptimismMintableERC20Factory.json"
fname = "node_modules/@eth-optimism/contracts-bedrock/artifacts/contracts/universal/OptimismMintableERC20.sol/OptimismMintableERC20.json"

# After replacement
fname = "node_modules/@eth-optimism/contracts-bedrock/forge-artifacts/OptimismMintableERC20Factory.sol/OptimismMintableERC20Factory.json"
fname = "node_modules/@eth-optimism/contracts-bedrock/forge-artifacts/OptimismMintableERC20.sol/OptimismMintableERC20.json"
```

In other locations, there are a few instances similar to this situation, and I'm not sure if it's necessary to make these modifications

**Comment by cpengilly** [comment]
@annieke can you answer the question about `@eth-optimism/contracts package`

**Comment by cpengilly** [comment]
proxy_ovm issue being tracked separately [here](https://github.com/ethereum-optimism/docs/issues/148)
