### ISSUE TITLE
[Chain Operators part]A potential issue that may need to be checked.

### ISSUE THREAD

**Issue by opfocus** [ethereum-optimism/docs#121]
Location: https://docs.optimism.io/chain-operators/create-l2-rollup
1. Quotation:  of the Optimism Superchain 
lost link

2. Quotation: out the Superchain Explainer
lost link

3. Quotation: and op-nethermind (coming soon).
Need to check if op-nethermind information needs updating.

4. Quotation: We recommend funding the accounts with the following amounts when using Sepolia:

Admin — 0.2 ETH
Proposer — 0.2 ETH
Batcher — 0.1 ETH

Validation is needed, especially for the admin's recommended balance

Location: https://docs.optimism.io/chain-operators/configuration
1. Quotation: this is the configuration file for the tutorial blockchain.
Description is outdated, currently using a script to generate the corresponding JSON files.

Location: https://docs.optimism.io/chain-operators/operations
1. Quotation: tip Synchronization takes time
Styles not applied

2. Quotation: peer to peer synchronization
lost link

Location: https://docs.optimism.io/chain-operators/explorer
1. Quotation: edit docker-compose-no-build-geth.yml to set ETHEREUM_JSONRPC_HTTP_URL to the correct URL.
Blockscout version update may have resulted in this information being outdated

Location: https://docs.optimism.io/chain-operators/sdk

Lib_AddressManager.json
Name outdated

Proxy__OVM_L1CrossDomainMessenger.json
Name outdated

Proxy__OVM_L1StandardBridge.json
Name outdated

   AddressManager: "0x....",   // Lib_AddressManager.json
   L1CrossDomainMessenger: "0x....",   // Proxy__OVM_L1CrossDomainMessenger.json  
   L1StandardBridge: "0x....",   // Proxy__OVM_L1StandardBridge.json
Name outdated

Location: https://docs.optimism.io/chain-operators/hacks/derivation
1. Quotation: Tutorial: Adding attributes to the derivation function.
lost link

Location: https://docs.optimism.io/chain-operators/hacks/execution
1. Quotation: Tutorial: Adding a precompile.
lost link

Location: https://docs.optimism.io/chain-operators/sample-hacks/adding-derivation-attributes
1. Quotation: Insert the burn transactions
This section's references are outdated compared to the latest source code updates

Location: https://docs.optimism.io/chain-operators/sample-hacks/adding-precompiles
1. Quotation: op-geth/core/vm/contracts.go.
Should we reference the default branch?

Location: https://docs.optimism.io/chain-operators/sample-hacks/modifying-predeploys
1. Quotation: predeployed contracts
Inconsistent references(link)

2. Quotation: ProxyAdmin
Should we reference the default branch

3. Quotation: upgrade(address,address)
Should we reference the default branch

Location: https://docs.optimism.io/chain-operators/chain-troubleshooting
.envrc.example
Changes in location within the default branch.

**Comment by cpengilly** [comment]
@opfocus We ask that you please limit issues to one item or page to make reviews and edits easier. This is just best practices for git issues. Thank you! 🙏🏾 😄
