### ISSUE TITLE
[Node Operator Guide]A potential issue that may need to be checked.

### ISSUE THREAD

**Issue by opfocus** [ethereum-optimism/docs#122]
Location: https://docs.optimism.io/node-operators/node-operator-guide
1. Quotation: Building a Node from Source
lost link

2. Quotation: Consult the documentation for
lost link

3. Quotation: op-geth requires: --op-network=op-sepolia  
(new flag?)??

4. Quotation: --network=sepolia \
In the previous context, different values were used in op-node requires: --network=op-sepolia

5. Quotation: :::danger It is imperative
Invalid style.

Location: https://docs.optimism.io/node-operators/json-rpc
 you can call the GasPriceOracle's l1BaseFee function
Need to connect to readproxycontract

Location: https://docs.optimism.io/node-operators/building-node/intro
1. Quotation: Hardware requirements
Inconsistent description.  https://docs.optimism.io/node-operators/node-operator-guide#system-requirements

2. Quotation: curl -L https://foundry.paradigm.xyz
Invalid style

3. Quotation: ::: info OP Mainnet Archive Node
Invalid style

Location: https://docs.optimism.io/node-operators/building-node/mainnet
Get the data directory
Duplicate content. Much of this section overlaps with https://docs.optimism.io/node-operators/data-directories. However, I don't believe this section should be deleted or merged.

**Comment by cpengilly** [comment]
fixed! Thank you!
