### ISSUE TITLE
[Wallets & CEXs+Tools part]A potential issue that may need to be checked.

### ISSUE THREAD

**Issue by opfocus** [ethereum-optimism/docs#123]
Location: https://docs.optimism.io/cex-wallet-developers/cex-support
1. Quotation: private rpc provider
maybe need link to tool-rpc providers

2. Quotation: have an OP Mainnet equivalent
Is it appropriate to use 'equivalent'? Cause most of the mapped tokens created have differences in functionality compared to the L1 tokens.

Location: https://docs.optimism.io/tools/rpc-providers
1. Quotation: make a PR.
Outdated link

Location: https://docs.optimism.io/tools/block-explorers
1. Quotation: see Regenesis History tutorial.
lost link

Location: https://docs.optimism.io/tools/javascript/sdk
Location: https://docs.optimism.io/tools/javascript/sdk-view-tx
Location: https://docs.optimism.io/tools/javascript/sdk-trace-tx
Location: https://docs.optimism.io/tools/javascript/sdk-estimate-gas
1. Quotation: supported directly, see the documentation
Supported networks listed in the linked target content are not comprehensive

Location: https://docs.optimism.io/tools/javascript/sdk-estimate-gas
1. Quotation: Setup  
No content

2. Quotation: displayResults
No content

Location: https://docs.optimism.io/tools/faucets
1. Quotation: using the L1StandardBridge.
Might be an unintelligible name

https://docs.optimism.io/tools/oracles
1. Quotation: provides a Gas Price Oracle
Might be an outdated link

Additional(I have not read the full text, please ignore it if it has been provided)
Maybe it is necessary to provide the superchain token list in the resources section of the documentation

**Comment by cpengilly** [comment]
@opfocus still going thru your feedback, but if you could focus each issue around just **one** page or feedback item, it would be greatly appreciated! It makes it easier to follow, update, and submit related PRs. Thanx! 💟
