### ISSUE TITLE
[FEEDBACK]OP MAINNET part

### ISSUE THREAD

**Issue by opfocus** [ethereum-optimism/docs#150]
Location: https://docs.optimism.io/getting-started-op-mainnet
Quotation: We have Hardhat's Greeter contract 
lost link

Location: https://docs.optimism.io/differences
Quotation: Address Aliasing
no content

Location: https://docs.optimism.io/op-networks
1. Quotation: *But it is not for production systems and is rate limited.-
Invalid style

2. Quotation: L1 Contract Addresses
Quotation: L2 Contract Addresses
lost link

Location: https://docs.optimism.io/identity/about-attestations
Quotation: begins with the Ethereum Attestation Service,
I did not access successfully

Location: https://docs.optimism.io/identity/contracts-eas
Quotation: JavaScript SDK
lost link

Location: https://docs.optimism.io/identity/optimist-profile#common-questions
Quotation: Use the EAS SDK
Might need to add link for EAS SDK

Location: https://docs.optimism.io/identity/optimist-profile#common-questions
Quotation: the Ethereum Attestation Service.
lost link

**Comment by cpengilly** [comment]
these issues have been addressed in several PRs. thank you for your contribution! :)
