### ISSUE TITLE
[AUDIT] Update solidity tutorial

### ISSUE THREAD

**Issue by cpengilly** [ethereum-optimism/docs#165]
## Brief Description of the Docs Request
Solidity tutorial needs updating

## Description of the Documentation You'd Like
update solidity tutorial so it feels more like tutorial, rather than guide
- Update for Sepolia
- Add step-by-step instructions for setting the greeter message

## Additional Context
this content was split off from a longer tutorial that merged hardhat, foundry, and solidity. The other tutorials no longer exist and solidity page needs to be transformed/transitioned into a tutorial.

**Comment by unworld11** [comment]
please assign it to me
