### ISSUE TITLE
[AUDIT] update sdk-view-tx

### ISSUE THREAD

**Issue by cpengilly** [ethereum-optimism/docs#199]
for this page: https://docs.optimism.io/builders/tools/javascript/sdk-view-tx

rename conclusion to `next steps`, and can be moved to the end to wrap up the tutorial.

**Comment by raebeatrose4** [comment]
Can you please assign this task to me?

**Comment by cpengilly** [comment]
Yes! Thank you in advance for contributing! :)

**Comment by cpengilly** [comment]
page recently updated so no longer need this!
