### ISSUE TITLE
[AUDIT] update analytics-tools

### ISSUE THREAD

**Issue by cpengilly** [ethereum-optimism/docs#200]
2 steps to update this page https://docs.optimism.io/builders/tools/monitoring/analytics-tools:
1. Update the list of OP Dashboards
    - [[OP Stack Chains - L1 Mainnet Activity & Fees Paid, L2 OP Chain Activity](https://dune.com/oplabspbc/op-stack-chains-l1-activity)](https://dune.com/oplabspbc/op-stack-chains-l1-activity)
    - [[OP Mainnet Protocol Metrics](https://dune.com/optimismfnd/Optimism)](https://dune.com/optimismfnd/Optimism)
    - [[Popular Apps on OP Mainnet and Project Usage Trends](https://dune.com/optimismfnd/Optimism-Project-Usage-Trends)](https://dune.com/optimismfnd/Optimism-Project-Usage-Trends)
    - [[OP Token House Delegates](https://dune.com/optimismfnd/optimism-op-token-house)](https://dune.com/optimismfnd/optimism-op-token-house)
    - [[Superchain NFTs](https://dune.com/oplabspbc/superchain-nfts)](https://dune.com/oplabspbc/superchain-nfts)
2. Add additional tools/resources (i.e. our github, defillama, growthepie)
    - DeFi Stats: https://defillama.com/
    - L2 Usage and comparison: https://www.growthepie.xyz/
    - OP Analytics (incentive tracking, helper functions, public analysis): https://github.com/ethereum-optimism/op-analytics
    - Contribute to NumbaNERDs: https://app.dework.xyz/optimism-community/main-space-35638/overview or requests: https://github.com/ethereum-optimism/op-analytics/issues

**Comment by 0xgun** [comment]
Please assign this issue to me.

**Comment by cpengilly** [comment]
sorry @0xgun, it looks like this issue already has a pending PR.
