### ISSUE TITLE
[AUDIT] Update getting started op-mainnet

### ISSUE THREAD

**Issue by cpengilly** [ethereum-optimism/docs#202]
[Getting Started with OP Mainnet](https://docs.optimism.io/chain/getting-started) could be more educational, or perhaps could be split into two documents:
- one that explains what OP Mainnet is and 
- another that acts like a getting started guide. Right now it immediately jumps into getting started without doing any exposition.

**WORK IN PROGRESS. STILL SCOPING THIS ISSUE.**

**Comment by Anton-dot911** [comment]
Hi. I'm new and have only recently started studying. And the very first and most obvious problem for me was these two points. "Beginning on OP Minet" and "First Contract." 
In the "Beginning on OP Minet" section, I wanted to find a clear understanding of the structure of the development environment and the relationships between its components. And after that, startening practicing and understanding how it works.

**Comment by accessor-io** [comment]
see [pull 208](https://github.com/ethereum-optimism/docs/pull/208)
request for review and approval,

**Comment by Anton-dot911** [comment]
сб, 25 лист. 2023 р. о 00:34 accessor-io ***@***.***> пише:

**Comment by cpengilly** [comment]
> Hi. I'm new and have only recently started studying. And the very first and most obvious problem for me was these two points. "Beginning on OP Minet" and "First Contract." In the "Beginning on OP Minet" section, I wanted to find a clear understanding of the structure of the development environment and the relationships between its components. And after that, startening practicing and understanding how it works.

Thanks for the feedback @Anton-dot911. We've recently updated the [first contract tutorial](https://docs.optimism.io/builders/dapp-developers/tutorials/first-contract), and we'd love to get your feedback on it. We are still working on the getting starting guide and need to scope the ask/request a bit more first.
