### ISSUE TITLE
[AUDIT] Update pause/unpause bridge to be tutorial

### ISSUE THREAD

**Issue by cpengilly** [ethereum-optimism/docs#204]
for this page https://docs.optimism.io/stack/op-stack-security/pause

- could be written as a tutorial to make more useful
- need specific steps for ‘changing the guardian’

**Comment by Violet-Bora-Lee** [comment]
@cpengilly Hi. Can you check the server?

![image](https://github.com/ethereum-optimism/docs/assets/6451384/b35d2272-e2e8-4639-8abe-10b765558075)
