### ISSUE TITLE
[DOCS] Update OP Networks Page

### ISSUE THREAD

**Issue by sbvegan** [ethereum-optimism/docs#254]
## Brief Description of the Docs Request

The OP Networks Page needs the following updates:
- add etherscan explorer for op sepolia: https://sepolia-optimism.etherscan.io/
- update the rollup config section
  - `op-node` needs the `network` flags parameter to be updated
  - `op-geth` needs to be mentioned, we're requiring `op-network` flag
- The contract addresses have their own page now. Should we remove them here or use the auto generated address functionality? 

## Description of the Documentation You'd Like

Just updated information here

## Links to Related Pages

- https://docs.optimism.io/chain/networks

## Additional Context

I saw these points when I was looking into providing OP Sepolia information

**Comment by AravindAkuthota** [comment]
@sbvegan  i want to work on this ...can  i go ahead ...

**Comment by sbvegan** [comment]
@AravindAkuthota yes please :)
