### ISSUE TITLE
[DOCS] clarify standard ERC20 requirements for the standard bridge

### ISSUE THREAD

**Issue by sbvegan** [ethereum-optimism/docs#29]
**Is your doc request related to a problem or existing docs? Please describe.**

A developer reported that there's not an EIP165 requirement to go from L1 to L2, but there is to go from L2 to L1. Their Ethereum Mainnet token is a vanilla ERC20, but their implementation on OP Mainnet is not.

**Describe the documentation you'd like**

Clarify the ERC20 requirements to use the standard bridge.

**Additional context**

https://github.com/ethereum-optimism/developer-support/issues/141

**Comment by cpengilly** [comment]
addressed in issue https://github.com/ethereum-optimism/docs/issues/73
