### ISSUE TITLE
[DESIGN] Add favicon to docs site

### ISSUE THREAD

**Issue by cpengilly** [ethereum-optimism/docs#291]
can we add a custom OP favicon to the docs site?

based on [nextra's documentation](https://nextra.site/docs/docs-theme/theme-configuration#favicon-glyph-experimental), it looks like they support emoji favicons out of the box which doesnt' seem like it's what we want, so I'll ask a designer for help :sweat_smile:

**Comment by pifafu** [comment]
Here's a high res asset:

![OP Logo (1)](https://github.com/ethereum-optimism/docs/assets/5679180/5cddc139-3b83-47e4-83e8-3b9974f37ace)
