### ISSUE TITLE
[DOCS] Add call out to the audited versions of our contracts

### ISSUE THREAD

**Issue by sbvegan** [ethereum-optimism/docs#344]
## Brief Description of the Docs Request

Lets call out what version of our smart contracts are deployed and audited.

## Description of the Documentation You'd Like

Add a callout or table to the smart contracts section to highlight what versions are audited/deployed.

## Links to Related Pages

- [Smart Contract Overview](https://docs.optimism.io/stack/protocol/smart-contracts)

**Comment by cpengilly** [comment]
duplicate issue, closing
