### ISSUE TITLE
[DOCS] add information about the differences between: `safe`, `unsafe`, and `finalized` block tags

### ISSUE THREAD

**Issue by sbvegan** [ethereum-optimism/docs#347]
## Brief Description of the Docs Request

Improve understanding of the different block tags. 

## Description of the Documentation You'd Like

I'd like a the differences between `safe`, `unsafe`, and `finalized` block tags included:

safe means all of the data to derive a L2 block has been included on L1
safe blocks only reorg if L1 reorg happens

unsafe means all of the data to derive a L2 block has been included on L1
unsafe blocks can reorg if the L1 reorgs or there was an issue sequencer

finalized means all of the data to derive a L2 block has been finalized on L1
no finalized block can be reorged

## Links to Related Pages

- It should probably go somewhere in the OP Stack > Protocol section: https://docs.optimism.io/stack/protocol/overview

## Additional Context

I've had different questions that boil down to understanding the difference between these. Things like rollback risks, confirmation delays for indexers, etc.

**Comment by smartcontracts** [comment]
Available here: https://docs.optimism.io/builders/dapp-developers/transactions/statuses

Will also go into protocol docs
