### ISSUE TITLE
[DOCS] Details on the sequencer fee vault

### ISSUE THREAD

**Issue by sbvegan** [ethereum-optimism/docs#366]
## Brief Description of the Docs Request

I think we need to add information about the fee vault and where transaction fees collected by the sequencer go. Generally the overview of that whole process should be added. This might be dipping into an area better served by the community docs, but there are technical aspects to it.

## Description of the Documentation You'd Like

Addition to the transaction fees page or a new page that the transaction fees page references.

## Links to Related Pages

- https://docs.optimism.io/stack/transactions/transaction-fees

## Additional Context

This [question](https://github.com/ethereum-optimism/developers/discussions/160) on the developer support forum highlighted that this information isn't easily visible.

**Comment by estheroche** [comment]
I can take this. kindly assign to me
