### ISSUE TITLE
[DOCS] add instructions on how to bridge ERC20s/ETH with multisig wallets

### ISSUE THREAD

**Issue by sbvegan** [ethereum-optimism/docs#37]
**Is your doc request related to a problem or existing docs? Please describe.**

One of our users lost their ERC20s by directly sending them to a bridge implementation contract.

**Describe the documentation you'd like**

Create new user documentation around bridging tokens and ether with multisig (Safe) wallets.

**Additional context**

**Comment by cpengilly** [comment]
callouts added to pages to address this issue
