### ISSUE TITLE
[DOCS] `Launch Support` Link Broken

### ISSUE THREAD

**Issue by boundless-forest** [ethereum-optimism/docs#387]
Our team wants to build and rollup based on Op Stack and try to reach out the official support team via `Launch Support`. But, it's doesn't work. Could you please help us? Or any other way to get support from the official team.

![image](https://github.com/ethereum-optimism/docs/assets/11801722/a69ba36e-a129-4fa8-8e73-019becdde482)

![image](https://github.com/ethereum-optimism/docs/assets/11801722/f894090a-dc61-48a6-b258-785a652f2be9)

**Comment by cpengilly** [comment]
link fixed! thank you so much for letting us know :)

**Comment by boundless-forest** [comment]
Thank you for your reply. I have submitted a launch support. But no feedback yet. I just want to confirm that if the support team received our request from the Darwinia team.

**Comment by cpengilly** [comment]
@boundless-forest this repo only manages the Optimism Developer docs, so unfortunately, I don't have any insight into the launch support process. I will make an inquiry for you 💟
