### ISSUE TITLE
[FEATURE] Track search terms within nextra site

### ISSUE THREAD

**Issue by cpengilly** [ethereum-optimism/docs#389]
we need to access/track keywords used in search bar by devs from within our nextra site. for more context: we have google console setup which lets us see terms devs search for while browsing google that lands them on [docs.optimism.io](http://docs.optimism.io/), but how we also need/want to track the search terms dev use while already on the site (using the search bar).

- Does nextra support algolia? 
- Yea I’ve seen it used with nextra before. You might want to wrap the existing nextra input instead of using a regular input like swr docs do but here is an example react component https://github.com/vercel/swr-site/blob/88d1b8affa7f1c344f3aaba229b51867b2cedc8d/components/docsearch.js

**Comment by roninjin10** [comment]
The nextra maintainer (who is also maintainer of swr) has an example of how to implement this here: https://github.com/vercel/swr-site/blob/88d1b8affa7f1c344f3aaba229b51867b2cedc8d/components/docsearch.js

**Comment by cpengilly** [comment]
feature request shifting to internal tracking system, ticket is closed for now until feature can be properly scoped and planned.
