### ISSUE TITLE
Feedback for “Creating Your Own L2 Rollup Testnet”

### ISSUE THREAD

**Issue by Ezra-Labs** [ethereum-optimism/docs#427]
On the step for Deploying the L1 Contracts...
The error message listed in the guide:
If you see a nondescript error that includes EvmError: Revert and Script failed then you likely need to change the IMPL_SALT environment variable. This variable determines the addresses of various smart contracts that are deployed via CREATE2. If the same IMPL_SALT is used to deploy the same contracts twice, the second deployment will fail. You can generate a new IMPL_SALT by running direnv allow anywhere in the Optimism Monorepo.

I am receiving this sort of error, but I follow the guide and attempt to rerun direnv allow, however this does not stop the error from coming through.

**Comment by smartcontracts** [comment]
Hi, this should be fixed now, can you confirm?

**Comment by Ezra-Labs** [comment]
Yes! I had marked it as answered in the thread. Thanks!
