### ISSUE TITLE
[DOCS] EVM equivalence wrong doc content

### ISSUE THREAD

**Issue by sbvegan** [ethereum-optimism/docs#43]
**Is your doc request related to a problem or existing docs? Please describe.**

**Describe the documentation you'd like**

https://community.optimism.io/docs/developers/build/differences/#opcode-differences

Context: https://github.com/mds1/evm-diff/issues/21

The COINBASE opcode returns the priority-fee recipient address of the L2 block, which is always the same, set to the SequencerFeeVault predeploy address. This may change in future upgrades.

The DIFFICULTY opcode was renamed to PREVRANDAO with EIP-4399, and post-Bedrock exposes the PREVRANDAO value of the latest L1 block (matching the L1 block exposed in the L1BlockInfo predeploy).

**Additional context**

**Comment by cpengilly** [comment]
@sbvegan can you tell me if the page still has this issue? https://docs.optimism.io/chain/differences#opcodes

**Comment by sbvegan** [comment]
@cpengilly looks good to me, when Canyon is live on mainnet, we'll have PUSH0. So we'll need to remove that in January.
