### ISSUE TITLE
[DOCS] ProtocolVersions contract address is missing

### ISSUE THREAD

**Issue by sbvegan** [ethereum-optimism/docs#430]
## Brief Description of the Docs Request

The contract address page is automatically updated by the super chain registry repo, but its missing the `ProtocolVersions` contract. 

## Description of the Documentation You'd Like

Update with the address included.

## Links to Related Pages

https://docs.optimism.io/chain/addresses

## Additional Context

https://github.com/ethereum-optimism/optimism/blob/develop/specs/superchain-upgrades.md#protocol-version

**Comment by cpengilly** [comment]
@smartcontracts can you help with this pls? 🙏🏾

**Comment by sbvegan** [comment]
Already added to this page: https://docs.optimism.io/stack/smart-contracts#protocolversions
