### ISSUE TITLE
Update required for Initialization via Genesis File on execution client

### ISSUE THREAD

**Issue by pcw109550** [ethereum-optimism/docs#441]
## Brief Description of the Docs Request

There is `Initialization via Genesis File` option while https://docs.optimism.io/builders/node-operators/management/configuration#configuring-op-geth .

OP-sepolia Genesis file is linked: https://networks.optimism.io/op-sepolia/genesis.json

However this genesis is outdated. Canyon hard fork related values must be added. Desired json form can be referenced here. https://github.com/testinprod-io/op-erigon/issues/113#issuecomment-1868561095

Whenever hard fork happens, this json should be updated.

**Comment by cpengilly** [comment]
>Whenever hard fork happens, this json should be updated.
Wondering if this can be automated in some way? @smartcontracts @sbvegan
