### ISSUE TITLE
[DOCS] add eip1559 Canyon configurations

### ISSUE THREAD

**Issue by sbvegan** [ethereum-optimism/docs#444]
## Brief Description of the Docs Request

Document the new configuration values that were added in the canyon upgrade

## Description of the Documentation You'd Like

Update the chain configuration page with `eip1559DenominatorCanyon`, the value is 250. There might be more additional configurations, we'll have to look into that or ask the client engineers.

## Links to Related Pages

https://docs.optimism.io/builders/chain-operators/management/configuration#eip-1559-gas-algorithm

**Comment by cpengilly** [comment]
>There might be more additional configurations, we'll have to look into that or ask the client engineers.
@annieke @K-Ho would you be able to point us in the right direction here? 🙏🏾

**Comment by sbvegan** [comment]
This information is included on this page: https://docs.optimism.io/builders/node-operators/network-upgrades#canyon
