### ISSUE TITLE
[DOCS] Bridging tokens from L1 to PGN

### ISSUE THREAD

**Issue by OPMattie** [ethereum-optimism/docs#45]
**Is your doc request related to a problem or existing docs? Please describe.**
Via PGN:
- Bridging tokens from L1 to PGN is currently under-documented, and there isn't clarity on how to best verify that token contracts will be correctly recognized on withdraw back to ETH mainnet
- Base DevRel also confirmed there is user confusion for what being on the superchain token list means, since it does not necessarily mean it ends up on the Base bridge.
- There is an opportunity to position the token list as a tool that can be built on for projects.

**Describe the documentation you'd like**
- In OP Stack docs, create new page that helps with the "L1 to PGN" use case above. Target audience is chain operators. Should be generalized to any OP Chain, not just PGN.
- Create a page or section detailing Superchain Token List, how to get on it, and what can be built with it.

**Comment by cpengilly** [comment]
update: tokenlist now lives in docs @ https://docs.optimism.io/tokenlist
