### ISSUE TITLE
[DOCS] Update Docker Setup

### ISSUE THREAD

**Issue by sbvegan** [ethereum-optimism/docs#46]
**Is your doc request related to a problem or existing docs? Please describe.**

`simple-optimism-node` will not be maintained by OPLabs so we should include a docker setup guide in our docs.

**Describe the documentation you'd like**

Take the configs from https://github.com/ethereum-optimism/developer-support/issues/64 and create a docker node setup guide. It should include: mainnet/testnet & full/archive details.

**Additional context**

**Comment by cpengilly** [comment]
we are now maintaining simple-optimism-node repo inhouse so closing this issue

**Comment by sbvegan** [comment]
Not technically in house at OP Labs, but we have a maintainer committed to the project
