### ISSUE TITLE
[DOCS] governance approved and audited smart contract call out

### ISSUE THREAD

**Issue by sbvegan** [ethereum-optimism/docs#472]
## Brief Description of the Docs Request

Clearly call out the what versions of the smart contracts are production ready. We only suggest governance approved and audited versions; but this is not clear enough in the docs.

## Description of the Documentation You'd Like

Add callouts or a formal description of the contract release process so this information is more available.

## Links to Related Pages

- https://docs.optimism.io/stack/protocol/smart-contracts
- https://docs.optimism.io/builders/chain-operators/tutorials/create-l2-rollup#smart-contracts

## Additional Context

We don't want people to deploy insecure contracts.

**Comment by sbvegan** [comment]
Release notes:
- https://github.com/ethereum-optimism/optimism/releases/tag/op-contracts%2Fv1.0.0
- https://github.com/ethereum-optimism/optimism/releases/tag/op-contracts%2Fv1.1.0
- https://github.com/ethereum-optimism/optimism/releases/tag/op-contracts%2Fv1.2.0
- https://github.com/ethereum-optimism/optimism/releases/tag/op-contracts%2Fv1.3.0-rc.1

**Comment by sbvegan** [comment]
https://github.com/ethereum-optimism/optimism?tab=readme-ov-file#development-and-release-process

**Comment by cpengilly** [comment]
@ZakAyesh @sbvegan also adding to list for Mach completion (Q1)

**Comment by sbvegan** [comment]
completed a while ago
