### ISSUE TITLE
Feedback on upgrade docs

### ISSUE THREAD

**Issue by mds1** [ethereum-optimism/docs#476]
Sharing some great feedback that @abcoathup gave on [twitter](https://twitter.com/abcoathup/status/1755398875916149083), I generally agree with all of these suggestion and think they would be really nice improvements to the docs.

---

1. Each upgrade in docs should have a table in each upgrade with details for Devnet, Testnet, mainnet (including governance & notice periods).  With links to the action (e.g. governance vote)
![image](https://github.com/ethereum-optimism/docs/assets/17163988/bab4d2f1-d80a-4aeb-86b2-e03a00a713a0)

2. The features of the upgrade should be described in the docs. Blog posts & announcements can point to the docs for technical details. Not the other way round with docs pointing to blog posts. Announce and do blog posts for each major step.
![image](https://github.com/ethereum-optimism/docs/assets/17163988/79ee9540-87dc-49f2-985c-c10ab00d14e1)

3. The overview is great but should have more detail for when you go to the docs for a specific upgrade.
![image](https://github.com/ethereum-optimism/docs/assets/17163988/5cf57a3d-d3df-4b69-a5d8-48c3f1126e9c)

4. Make the menu header clickable.  At least on mobile.  To make it easier to navigate.
![image](https://github.com/ethereum-optimism/docs/assets/17163988/2ee68dba-859c-4e4b-a670-5bec48145783)

5. Add Citizens house veto in the detail of each upgrade. You should be able to get to all the info about an upgrade from the docs.
![image](https://github.com/ethereum-optimism/docs/assets/17163988/058b81bb-a7a5-4282-80ab-8c5691fa7a00)

6. Add info on the upgrade naming scheme.  Even if its whatever cool name the dev team wants. A one liner on what the name means.
![image](https://github.com/ethereum-optimism/docs/assets/17163988/0b3fae66-b950-420e-a636-f4445e88fdd1)

7. Keep the docs updated.  Ecotone on OP Goerli already happened.
![image](https://github.com/ethereum-optimism/docs/assets/17163988/db89d11a-ecb8-4552-8aec-aed4db94cbe3)

8. overall make it easy to find out all about an upgrade and when it happened.  Devs shouldn't need to hunt around for ages to find info.  Upgrades should be celebrated and shouted about. Bring on Ecotone and blobs.

**Comment by sbvegan** [comment]
All but point (4) gets addressed in https://github.com/ethereum-optimism/docs/pull/515

**Comment by cpengilly** [comment]
#4 is a feature request since it's not natively supported in nextra. we'll have to put in for a design change, so I'll track this separately. closing this ticket.
