### ISSUE TITLE
Suggest an FAQ item page in Github

### ISSUE THREAD

**Issue by noobmanog** [ethereum-optimism/docs#490]
### FAQ Category

Revise an existing faq item

### What page will this FAQ item live?

https://github.com/ethereum-optimism/docs/issues/new?assignees=&labels=documentation%2Cfaq%2Ccommunity-request&projects=&template=suggest_faq_item.yaml&title=Suggest+an+FAQ+item

### write the question from a developer's perspective

Before submitting this suggestion, be sure to read our expectations for [FAQ content](https://docs.optimism.io/contribute/style-guide#faqs).
For an example FAQ guide with question+answer pairs, see [Security Model FAQ](https://docs.optimism.io/security/faq#security-model-faq).

### answer the question identified above as best as possible

Before submitting this suggestion, be sure to read our expectations for [FAQ content](https://docs.optimism.io/connect/contribute/style-guide).
For an example FAQ guide with question+answer pairs, see [Security Model FAQ](https://docs.optimism.io/chain/security/faq#security-model-faq).

### Additional context

broken links

**Comment by noobmanog** [comment]
![image](https://github.com/ethereum-optimism/docs/assets/97117654/108b2625-af86-4fd2-b9b7-e46905a999dc)

**Comment by cpengilly** [comment]
@noobmanog can you pls clarify what page has broken links? 🙏🏾 It is not clear from the PR. thank you!

**Comment by cpengilly** [comment]
closing, no followup from original poster
