### ISSUE TITLE
[DOCS] OP Mainnet archive node snapshot 404 not found

### ISSUE THREAD

**Issue by Chomtana** [ethereum-optimism/docs#496]
## Brief Description of the Docs Request

<img width="707" alt="image" src="https://github.com/ethereum-optimism/docs/assets/4103490/08326379-a1c5-40f2-bbeb-32ea8438cf03">

<img width="205" alt="image" src="https://github.com/ethereum-optimism/docs/assets/4103490/21035d97-16e9-4692-9f77-5a82d000cb59">

## Description of the Documentation You'd Like
It should not be 404 and must download the snapshot archive file

## Links to Related Pages
https://docs.optimism.io/builders/node-operators/management/snapshots

https://datadirs.optimism.io/mainnet-2024-01-26.tar.zst

## Additional Context
@sbvegan @cpengilly @smartcontracts

**Comment by imtipi** [comment]
![image](https://github.com/ethereum-optimism/docs/assets/27230181/35f0f1e5-57d0-43b2-8fac-7153cbfd80fd)
should we just update the link?

**Comment by imtipi** [comment]
> Except we will only say "latest" and not fix the date in docs.
acceptable i think,except i don't know how to display the sha256sum,have to change it to the link as well
or,even just display https://datadirs.optimism.io/ and let user choose on their own(if they want other version)

**Comment by imtipi** [comment]
> It can't just update the link because the link is dynamic and changes over time.
> 
> Except we will only say "latest" and not fix the date in docs.

acceptable i think,except i don't know how to display the sha256sum,have to change it to the link as well
or,even just display https://datadirs.optimism.io/ and let user choose on their own(if they want other version)

**Comment by smartcontracts** [comment]
https://github.com/ethereum-optimism/docs/pull/498/files

Will fix
