### ISSUE TITLE
Change "The Optimism Monorepo" to "The OP Stack Monorepo" in the devdocs

### ISSUE THREAD

**Issue by sbvegan** [ethereum-optimism/docs#51]
https://linear.app/optimism/issue/DEVRL-1088/change-the-optimism-monorepo-to-the-op-stack-monorepo-in-the-devdocs

**Comment by sbvegan** [comment]
@smartcontracts @cpengilly this was something that was in linear that I just migrated over. I have no historical context on this tho.

**Comment by cpengilly** [comment]
okay, closing the ticket for now.
