### ISSUE TITLE
Update security FAQ page

### ISSUE THREAD

**Issue by cpengilly** [ethereum-optimism/docs#535]
this part is outdated: 

Next gen fault proofs
As part of the OVM 2.0 upgrade, the Optimism fault proof mechanism had to be temporarily disabled. This means that users of the OP Mainnet network currently need to trust the Sequencer node (run by Optimism Foundation) to publish valid state roots to Ethereum. You can also read more about our security model.

We're making progress on the upgrade fault proof mechanism and we expect to productionize our work in 2023. You can keep up with developments in the Cannon repository.

**Comment by smartcontracts** [comment]
There's a draft for this here: https://github.com/ethereum-optimism/docs/pull/329
