### ISSUE TITLE
[TUTORIAL] Add a grafana + prometheus dashboard for node and chain operators

### ISSUE THREAD

**Issue by sbvegan** [ethereum-optimism/docs#556]
### Tutorial title

Add a grafana + prometheus dashboard for node and chain operators

### Tutorial description

dashboard for monitoring

### Tutorial tags

nodes, chains

### Skill level

Advanced

### Hosted on Optimism.io or hosted elsewhere?

Hosted on optimism.io

**Comment by cpengilly** [comment]
duplicate issue
