### ISSUE TITLE
[DOCS] take blob info from `v1.7.2-rc.3` release notes and work them into the docs

### ISSUE THREAD

**Issue by sbvegan** [ethereum-optimism/docs#560]
## Brief Description of the Docs Request

These [release notes](https://github.com/ethereum-optimism/optimism/releases/tag/op-batcher%2Fv1.7.2-rc.3) have good information that we should work into the docs.

## Description of the Documentation You'd Like

Add this content to our chain operator blob pages and probably carve out the batcher config section

## Links to Related Pages

- https://docs.optimism.io/builders/chain-operators/management/blobs

## Additional Context
Provide any additional context about this documentation request. What problems did you run into that caused you to make this request? 
Which existing documentation pages did you already try as a solution to your problem? Why do you think the requested page(s) will be beneficial to developers in the Optimism Collective?

**Comment by estheroche** [comment]
I can take this. can you assign this to me?

**Comment by sbvegan** [comment]
Hey @estheroche, thanks for taking this on! Let me know if you need more context

**Comment by estheroche** [comment]
@cpengilly please help, i have been facing an error trying to install [install pnpm] on my Macbook terminal. 

mac@Macs-MacBook-Pro-4 docs %  install pnpm 
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
       
       this is the error.

please how can i rectify this? so that i can contribute

**Comment by cpengilly** [comment]
@estheroche sorry! when we didn't hear back, I took on the issue myself, so let's find you another issue! In the meantime, I will have devsupport reach out to resolve the pnpm install error. 💟

**Comment by estheroche** [comment]
@cpengilly thank you for your response

**Comment by estheroche** [comment]
@cpengilly i will be expecting feedback.

**Comment by cpengilly** [comment]
@estheroche I believe we might have fixed the issue. Can you try pnpm install again and let us know?

**Comment by estheroche** [comment]
@cpengilly its working now. thank you
