### ISSUE TITLE
[feature request]  make node tutorials customizable

### ISSUE THREAD

**Issue by sbvegan** [ethereum-optimism/docs#564]
## Brief Description of the Docs Request

Give node operators selector options to spin up a custom node tutorial:

- OP Mainnet vs OP Testnet
- full vs archive node
- if archive, do you want legacy execution?
- etc.

These inputs will spit out one tutorial with the necessary steps.

## Description of the Documentation You'd Like

- This feature will simplify node operator steps, so they only get the information they need for their setup
- Make the components of the tutorial modular which makes updating the docs simpler because its one place to make changes

## Links to Related Pages

- https://docs.optimism.io/builders/node-operators/tutorials/node-from-source
- https://docs.optimism.io/builders/node-operators/tutorials/mainnet
- https://docs.optimism.io/builders/node-operators/tutorials/testnet

## Additional Context

Feedback from Kev and engineering

**Comment by cpengilly** [comment]
shifted to feature prior matrix for tracking, so closing this issue
