### ISSUE TITLE
[DOCS] get rollup config for chains in the superchain-registry

### ISSUE THREAD

**Issue by sbvegan** [ethereum-optimism/docs#590]
## Brief Description of the Docs Request

Document how to get the rollup config from the op-node

## Description of the Documentation You'd Like

Add the folling information to the node operations page under chain management:

You can do this:
```
./bin/op-node networks dump-rollup-config --network=sepolia   
{
  "genesis": {
    "l1": {
      "hash": "0x48f520cf4ddaf34c8336e6e490632ea3cf1e5e93b0b2bc6e917557e31845371b",
      "number": 4071408
    },
    "l2": {
      "hash": "0x102de6ffb001480cc9b8b548fd05c34cd4f46ae4aa91759393db90ea0409887d",
      "number": 0
    },
    "l2_time": 1691802540,
    "system_config": {
      "batcherAddr": "0x8f23bb38f531600e5d8fddaaec41f13fab46e98c",
      "overhead": "0x00000000000000000000000000000000000000000000000000000000000000bc",
      "scalar": "0x00000000000000000000000000000000000000000000000000000000000a6fe0",
      "gasLimit": 30000000
    }
  },
  "block_time": 2,
  "max_sequencer_drift": 600,
  "seq_window_size": 3600,
  "channel_timeout": 300,
  "l1_chain_id": 11155111,
  "l2_chain_id": 11155420,
  "regolith_time": 0,
  "canyon_time": 1699981200,
  "delta_time": 1703203200,
  "ecotone_time": 1708534800,
  "batch_inbox_address": "0xff00000000000000000000000000000011155420",
  "deposit_contract_address": "0x16fc5058f25648194471939df75cf27a2fdc48bc",
  "l1_system_config_address": "0x034edd2a225f7f429a63e0f1d2084b9e0a93b538",
  "protocol_versions_address": "0x79add5713b383daa0a138d3c4780c7a1804a8090",
  "da_challenge_address": "0x0000000000000000000000000000000000000000",
  "da_challenge_window": 0,
  "da_resolve_window": 0,
  "use_plasma": false
}
```

## Additional Context

- But this will only work if your chain is already in the superchain-registry (and the op-node has been updated to pull those changes in from the registry).
- So this won't help any chain operator trying to generate this data in order to submit it to the registry.
- The --network=sepolia flag allows the tool to pick up the appropriate data from the registry
- it uses the OPChains mapping under the hood, so we have the power soon to decide whether the allowed values for --network should include frontier chains or not.

thank you @geoknee!

**Comment by cpengilly** [comment]
@JeffreyJoel would you be interested in taking this issue?

**Comment by JeffreyJoel** [comment]
@cpengilly, I am open to working on this, but I would like a bit more clarity on this.

**Comment by cpengilly** [comment]
@JeffreyJoel I agree! let's find you a diff issue to work on. We'll be in touch soon! 💟

**Comment by JeffreyJoel** [comment]
@cpengilly, I'm sorry for not being able to work on this sooner
