### ISSUE TITLE
[DOCS] add the OP Sepolia to Sepolia withdrawal time

### ISSUE THREAD

**Issue by sbvegan** [ethereum-optimism/docs#598]
## Brief Description of the Docs Request

Post fault proofs the withdrawal period is longer, but how long is it? hmmmm

## Description of the Documentation You'd Like

update the testnet withdrawal time

## Links to Related Pages

- https://docs.optimism.io/builders/app-developers/bridging/messaging#for-l2-to-l1-transactions
- honestly there is probably more, we just need to go through all the bridging pages to check

## Additional Context

- might be a good opportunity for some content reuse refactoring

**Comment by cpengilly** [comment]
duplicate issue, closing
