### ISSUE TITLE
[DOCS] Add new page about superchain-registry

### ISSUE THREAD

**Issue by sbvegan** [ethereum-optimism/docs#602]
## Brief Description of the Docs Request

The superchain registry is still a wip but soon we'll be having chains making PRs. 

## Description of the Documentation You'd Like

Overview of the registry and point to the contributing doc in the registry repo

## Links to Related Pages

New page under the Op Stack section

## Additional Context

https://github.com/ethereum-optimism/superchain-registry

**Comment by estheroche** [comment]
can you please assign to me, i want to handle this

**Comment by cpengilly** [comment]
@estheroche it's all yours! 💟

**Comment by estheroche** [comment]
@cpengilly thank you

**Comment by cpengilly** [comment]
pausing while working out details @estheroche we have the PR still pending and might use some of the content/details. we'll keep you posted!

**Comment by estheroche** [comment]
@cpengilly alright will be waiting for your feedback
