### ISSUE TITLE
[DOCS] OP Sepolia withdrawal time is not seconds anymore

### ISSUE THREAD

**Issue by lucadonnoh** [ethereum-optimism/docs#612]
https://github.com/ethereum-optimism/docs/blob/ad3d9c32d90992f8367bfdd8227302677a9b4aec/pages/builders/app-developers/tutorials/cross-dom-bridge-eth.mdx?plain=1#L245

**Comment by cpengilly** [comment]
per @sbvegan: We could add a general callout that we're testing fault proofs on OP Sepolia, point to the blog post, and say that withdrawal times currently reflect the mainnet time
