### ISSUE TITLE
[DOCS] Docs Multilingual Support

### ISSUE THREAD

**Issue by 22Xy** [ethereum-optimism/docs#623]
I've been exploring the OP Stack documentation and have found it to be exceptionally informative, with tutorials that are easy to navigate. I believe that extending support to include additional languages would benefit a broader audience. Are there any plans for multilingual documentation? If so, I would be eager to contribute to Chinese translations for tutorials, such as the one on creating an L2 rollup (https://docs.optimism.io/builders/chain-operators/tutorials/create-l2-rollup)

Thank you!

**Comment by cpengilly** [comment]
hi @22Xy we are working to setup for language/localization support and would appreciate your help! I think we'll be using Crowdin once we're all setup for translating the developer docs, but we'll def share details with the collective when we get to that point. I'll also pass this note along to our DevRel team to see if we can get this project mobilized sooner! 💟

**Comment by cpengilly** [comment]
closing this ticket for now, but we will be in touch with the community soon!
