### ISSUE TITLE
Withdrawal Flow Update

### ISSUE THREAD

**Issue by cpengilly** [ethereum-optimism/docs#642]
I am reading the doc <https://docs.optimism.io/stack/protocol/withdrawal-flow>
<https://github.com/ethereum-optimism/optimism/blob/62c7f3b05a70027b30054d4c8974f44000606fb7/op-proposer/proposer/l2_output_submitter.go#L312-L320|proposes a new output> link point to an old version or the proposer code.
the new code is <https://github.com/ethereum-optimism/optimism/blob/4a3d3fb444f50bed6a6991785ea5634e0efa07a4/op-proposer/proposer/driver.go#L311|here>

**Comment by richardgreg** [comment]
I'd like to work on this

**Comment by JeffreyJoel** [comment]
Hi @cpengilly, I would love to work on this

**Comment by cpengilly** [comment]
hi @richardgreg it's yours!
@JeffreyJoel I'll ping you for a diff issue to see if you're interested 💟

**Comment by JeffreyJoel** [comment]
@cpengilly, no problem

**Comment by cpengilly** [comment]
@JeffreyJoel would you be interested in issue #590 ?
