### ISSUE TITLE
[DOCS] transaction status 

### ISSUE THREAD

**Issue by sbvegan** [ethereum-optimism/docs#649]
## Brief Description of the Docs Request
Write a clear and concise description of the docs request. For example, is the request related to an existing page or are you suggesting a brand new docs page?

## Description of the Documentation You'd Like

update the sequencer window from 24 hours to 12 hours

## Links to Related Pages

https://docs.optimism.io/builders/app-developers/transactions/statuses

## Additional Context
Provide any additional context about this documentation request. What problems did you run into that caused you to make this request? 
Which existing documentation pages did you already try as a solution to your problem? Why do you think the requested page(s) will be beneficial to developers in the Optimism Collective?

**Comment by MukulKolpe** [comment]
Hey @sbvegan, can I work on this issue? And just to confirm, should this update be applied to both the "Published to Ethereum / Safe" and "Finalized" subsections?
