### ISSUE TITLE
Feedback for “Transaction Fees on OP Mainnet”

### ISSUE THREAD

**Issue by OPMattie** [ethereum-optimism/docs#654]
Couple smol notes:

Page calls out that Ecotone hasn't yet been approved by governance, but it was approved in Mar 2024

> The L1 Data Fee formula would change with the proposed Ecotone upgrade. Ecotone has not yet been approved by Optimism Governance. Refer to the [Network Upgrade Overview](https://docs.optimism.io/builders/node-operators/network-upgrades/overview) to check when the Ecotone upgrade is scheduled to activate on OP Sepolia and OP Mainnet.

Bullet in the Ecotone section has duplicated phrase:

> Two new scalar parameters that independently scale the base fee blob base fee.

**Comment by cpengilly** [comment]
first item addressed, along with few other related updates. second item is not a duplicate, but added clarification around that (base fee and blob base fee are two parameters that must be set by chain ops)
