### ISSUE TITLE
[DOCS] OP Stack 'Components' image is out of date

### ISSUE THREAD

**Issue by OPMattie** [ethereum-optimism/docs#673]
## Brief Description of the Docs Request
We received feedback that this page is becoming out of date with how it presents different components, such as for DA:

https://docs.optimism.io/stack/components

## Links to Related Pages
https://docs.optimism.io/stack/components

## Additional Context
If time allows, let's consider asking Design for an updated graphic rather than using excalidraw.

Some notes that might be helpful:
- Are the components flagged as "in development" or "proposed" still in that same state?
- DA has new features coming out and might need revision
- 4844 under DA layer is marked as proposed, but has shipped

**Comment by cpengilly** [comment]
@pifafu wondering if you can assist with this?

**Comment by pifafu** [comment]
Yep, adding it to my backlog!

I'll spin up a Figma and we can async align on what needs to be updated to reflect reality. Coming soon.

**Comment by cpengilly** [comment]
image removed for now
