### ISSUE TITLE
[DOCS] Revise transaction fees/gas estimate page

### ISSUE THREAD

**Issue by cpengilly** [ethereum-optimism/docs#69]
problem: [Trouble with gas estimate on OP Chains](https://github.com/ethereum-optimism/developer-support/discussions/196) (5). Developers often time have trouble estimating the cost of gas fees on OP Chains. This has been improved with the developer experience pod’s [fee-estimation](https://github.com/ethereum-optimism/optimism/tree/develop/packages/fee-estimation) library. However, there is still general developer confusion on how L2 gas fees work.

Solution: The confusion is around putting it all together. EIP1559 on L1 and L2, is something folks are still wrapping their head around. we should rewrite [the transaction fees page](https://docs.optimism.io/stack/transaction-fees/overview) and split it into 
- [ ] overview: give context on how estimation and send are 2 separate problems, and overall context on how to read this page. how to estimate fees easily: best practice for devs is to let the wallet set it. Likely @eth-optimism/fee-estimation until op-viem ships is the best way
- [ ] frontend estimation use: You can use the sdk, [fee-estimation](https://github.com/ethereum-optimism/optimism/tree/develop/packages/fee-estimation), or follow the explanation on this page, especially in the “displaying fees to users” section
- [ ] backend sending use (the core of the confusion from that issue): This is exactly like ethereum, just need the L2 execution fee section and the “sending transactions section”
- [ ] faq section (see below)

**Comment by cpengilly** [comment]
adding note here and removing duplicate issue:
about op-viem transactions: One reason we went with ‘’’estimateFees’’’ is because it's an action that will exist on non op chains. On ethereum estimateFees would just do ‘’’gasPrice * gasUsed’’’ whille on OP chains it's ‘’’gasPrice * gasUsed + L1GasFee’’’ but from developer/user point of view they don't have to think about that they just call ‘’’viemClient.estimateFees()’’’

Other FAQs to address:  wouldn’t devs likely send their transaction directly with an ‘’’eth_sendRawTransaction’’’? Likely abstracted away with a library like viem?

**Comment by cpengilly** [comment]
@sbvegan dropping your gas FAQ questions here:

The following are questions that developer support has encountered in the past.

- Does the **`eth_estimateGas` RPC method estimate the total L1 + L2 gas cost?**

No, `eth_estimateGas` only estimates the gas on the L2.

************Note:************ we also get this general question for `maxFeePerGas` and `eth_gasprice`

- How do I estimate the L1 gas cost?

Utilize the functions in the `GasPriceOracle`

https://github.com/ethereum-optimism/optimism/blob/v1.1.4/packages/contracts-bedrock/src/L2/GasPriceOracle.sol

- Can I limit the L1 gas I’m willing to spend? Does setting the `gasLimit` on transactions account for L1?

- How do I make a good gas estimate before submitting my transaction?

******Note:****** this question is usually for backend developers

- How do I provide gas estimates for my frontend?

[sdk.optimism.io](http://sdk.optimism.io/)

https://github.com/ethereum-optimism/optimism/tree/develop/packages/fee-estimation

**Comment by smartcontracts** [comment]
Resolved now
