### ISSUE TITLE
Feedback for “Deploying Your Contracts for Free on the Superchain”

### ISSUE THREAD

**Issue by rbio7** [ethereum-optimism/docs#700]
I do not have a Coinbase account, do you support other KYC methods?

**Comment by cpengilly** [comment]
@rbio7 thanks for the question! The deployment rebate is an initial experiment to learn if developers find free deployments valuable. If we learn that developers find this feature valuable, we will iterate on this product to make it more seamless. 

What other KYC method would you find most valuable? I'll be happy to pass the information along to our team! 💟
