### ISSUE TITLE
Getting error: Failed to get EIP-1559 fees

### ISSUE THREAD

**Issue by mohit6b** [ethereum-optimism/docs#709]
When using this command as suggested in docs: 
```forge script scripts/Deploy.s.sol:Deploy --private-key $GS_ADMIN_PRIVATE_KEY --broadcast --rpc-url $L1_RPC_URL --slow```
Getting this error: 
Getting error: Failed to get EIP-1559 fees

Even though the account is fully funded. Also not able to find in faq's and troubleshooting.
![Uploading Screenshot 2024-05-22 at 8.25.13 PM.png…]()

**Comment by krofax** [comment]
@mohit6b The image you provided isn't displaying can you provide another image and with a better description of the issue, and the particular tutorial you used.
Once you get all of that, please reopen this issue.
Thanks.
