### ISSUE TITLE
[DOCS] High-level explanation of Fault Proofs in the Overview section

### ISSUE THREAD

**Issue by PaulRBerg** [ethereum-optimism/docs#715]
## Brief Description of the Docs Request

I would like the overview section of the documentation on Fault Proofs to be simplified and rewritten.

## Description of the Documentation You'd Like

I've read the current docs multiple times without understanding much about the fault proofs work, at a high level.

The documentation feels rather 'abrupt' - it jumps straight to explaining the low-level concepts without giving a high-level overview.

## Links to Related Pages

https://docs.optimism.io/stack/protocol/fault-proofs/overview

## Additional Context

I understood more about how the fault proofs work by reading this summary written by Georgios:

https://x.com/gakonst/status/1489258844429553669

**Comment by sbvegan** [comment]
related: https://github.com/ethereum-optimism/docs/issues/655

**Comment by sbvegan** [comment]
Thanks for the feedback, I tend to agree. We'll see what we can do

**Comment by OPMattie** [comment]
@PaulRBerg we've since updated this page now that Fault Proofs is live on OP Mainnet:

https://docs.optimism.io/stack/protocol/fault-proofs/explainer

We'd love your feedback on if this is more what you were looking for.

**Comment by PaulRBerg** [comment]
Thanks @OPMattie, it looks good now! Closing the issue.
