### ISSUE TITLE
[FAUCET] Add PR title

### ISSUE THREAD

**Issue by Sintayew4** [ethereum-optimism/docs#747]
### Faucet Name

Optimize

### Faucet Description

#

### Faucet URL

https://github.com/ethereum-optimism/developers/blob/main/community/tools/faucets.md

### Supported Networks

- [X] OP Goerli
- [X] OP Sepolia
- [X] Base Goerli
- [X] Base Sepolia
- [X] Lyra Sepolia
- [X] Mode Sepolia
- [X] Orderly Sepolia
- [X] PGN Sepolia
- [X] Zora Sepolia

### When did the product go live?

Yes

### Is the product open source?

Yes

### GitHub URL

https://github.com/ethereum-optimism/developers/blob/main/community/tools/faucets.md

### Additional context

#

**Comment by Sintayew4** [comment]
- [ ] 747

**Comment by Sintayew4** [comment]
> ### Faucet Name
> Optimize
> 
> ### Faucet Description
> ### Faucet URL
> https://github.com/ethereum-optimism/developers/blob/main/community/tools/faucets.md
> 
> ### Supported Networks
> * [x]  OP Goerli
> * [x]  OP Sepolia
> * [x]  Base Goerli
> * [x]  Base Sepolia
> * [x]  Lyra Sepolia
> * [x]  Mode Sepolia
> * [x]  Orderly Sepolia
> * [x]  PGN Sepolia
> * [x]  Zora Sepolia
> 
> ### When did the product go live?
> Yes
> 
> ### Is the product open source?
> Yes
> 
> ### GitHub URL
> https://github.com/ethereum-optimism/developers/blob/main/community/tools/faucets.md
> 
> ### Additional context

**Comment by cpengilly** [comment]
@Sintayew4 You can go ahead and add your faucet to the [community page](https://github.com/ethereum-optimism/developers/blob/main/community/tools/faucets.md), using a PR. You will also need a product description in addition to the info above. 💟
