### ISSUE TITLE
[RPC PROVIDER] Add PR title

### ISSUE THREAD

**Issue by Sintayew4** [ethereum-optimism/docs#748]
### RPC Provider Name

Optimize 

### RPC Provider Description & Pricing

#

### RPC Provider URL

https://github.com/ethereum-optimism/developers/blob/main/community/tools/node-providers.md

### Supported Networks

- [X] OP Mainnet
- [X] OP Goerli
- [X] OP Sepolia

### When did the product go live?

Yes

### Is the product open source?

Yes

### GitHub URL

https://github.com/ethereum-optimism/developers/blob/main/community/tools/node-providers.md

### Documentation URL

https://github.com/ethereum-optimism/developers/blob/main/community/tools/node-providers.md

### Additional context

- [ ]

**Comment by Sintayew4** [comment]
#748

**Comment by cpengilly** [comment]
@Sintayew4 you can go ahead and add Optimize to the [Node Providers community listing](https://github.com/ethereum-optimism/developers/blob/main/community/tools/node-providers.md). You'll need a brief product description in addition to the info above 💟
