### ISSUE TITLE
Forced Withdrawal for OP stack rollup

### ISSUE THREAD

**Issue by krofax** [ethereum-optimism/docs#840]
Is forced withdrawal possible for OP stack rollups?

[Slack Message](https://oplabs-pbc.slack.com/archives/C02KCKY69ST/p1724084774174379?thread_ts=1724061766.742199&cid=C02KCKY69ST)

**Comment by imtipi** [comment]
https://superbridge.app/
https://github.com/superbridgeapp/superbridge-app
superbridge has a Escape hatch which works like force withdrawal,but I never tested it yet
