### ISSUE TITLE
[TUTORIAL] Problem in the Build the Source Code section in create op rollup tutorial

### ISSUE THREAD

**Issue by Hazem-dh** [ethereum-optimism/docs#846]
### Tutorial title

Issues when executing make command

### Tutorial description

I followed the OP stack Docs to [create a rollup](https://docs.optimism.io/builders/chain-operators/tutorials/create-l2-rollup) on Sepolia Testnet

In section  **6 -Build the various packages inside of the Optimism Monorepo**  i encounter the following error 

![screen1](https://github.com/user-attachments/assets/c9b7e453-0ecb-4353-8108-69c32f45344e)

### Tutorial tags

tutorial

### Skill level

Intermediate

### Hosted on Optimism.io or hosted elsewhere?

Hosted on optimism.io

### Additional context

i am using the branch tutorials/chain

**Comment by opfocus** [comment]
I'm running it and no errors are found, what is your go version

**Comment by Hazem-dh** [comment]
I have the following dependencies installed 

![image](https://github.com/user-attachments/assets/29346e62-9bad-49b1-9834-82fe8faaf055)

and i am using Ubuntu 20.04.6 LTS
I succeeded to solve that problem but now another similar one occured 

![image](https://github.com/user-attachments/assets/890a0336-e9cf-4fea-9790-d7f8d19a6c7d)

**Comment by opfocus** [comment]
I have been using version 1.21 of go.
I'm not sure if this will have an impact. What I'm sure is that version 1.20 of go cannot be used.

**Comment by krofax** [comment]
@Hazem-dh can you downgrade to version 1.21 of GO, and try again, and please revert here?

**Comment by Hazem-dh** [comment]
@krofax  i downgraded to version 1.21.0 and the command works , thank you

**Comment by opfocus** [comment]
@Hazem-dh  
Is the higher Go version being unavailable a known issue, or is it just a random error?

**Comment by krofax** [comment]
@Hazem-dh I'm closing this issue.
