### ISSUE TITLE
[ERROR] Tutorials：Creating Your Own L2 Rollup Testnet   issue

### ISSUE THREAD

**Issue by opfocus** [ethereum-optimism/docs#849]
**Description:**

When running `op-geth`, I encountered the following error:

```
geth/datadir/geth/chaindata/ancient/chain readonly=false
Fatal: Failed to register the Ethereum service: incompatible state scheme, stored: path, provided: hash
```

This error was resolved by performing the following steps:

1. Remove the existing `datadir`:
   ```bash
   rm -rf datadir
   ```
2. Recreate the `datadir`:
   ```bash
   mkdir datadir
   ```
3. Reinitialize with the following command:
   ```bash
   build/bin/geth init --datadir=datadir --state.scheme=hash genesis.json
   ```

During the execution of the `build/bin/geth init --datadir=datadir --state.scheme=hash genesis.json` command, I encountered another error:

```log
ERROR[08-23|17:11:15.047] Head block is not reachable
INFO [08-23|17:11:15.362] Persisted trie from memory database      nodes=3137 size=453.32KiB time=17.070932ms gcnodes=0 gcsize=0.00B gctime=0s livenodes=0 livesize=0.00B
INFO [08-23|17:11:15.535] Successfully wrote genesis state         database=chaindata hash=fb7ed5..9b1a0f
INFO [08-23|17:11:15.535] Defaulting to pebble as the backing database
INFO [08-23|17:11:15.535] Allocated cache and file handles         database=/root/op-geth/datadir/geth/lightchaindata cache=16.00MiB handles=16
INFO [08-23|17:11:15.572] Opened ancient database                  database=/root/op-geth/datadir/geth/lightchaindata/ancient/chain readonly=false
INFO [08-23|17:11:15.572] State scheme set by user                 scheme=hash
INFO [08-23|17:11:15.572] Writing custom genesis block
ERROR[08-23|17:11:15.588] Head block is not reachable
```

I chose to ignore this error for now, as it didn’t seem to affect subsequent operations. However, I believe this issue should be investigated to determine its cause and to ensure that it does not lead to further problems down the line.

**Steps to Reproduce:**

1. Run `op-geth` with the specified configurations.
2. Execute the above steps to resolve the initial error.
3. Observe the output for the "Head block is not reachable" error during `geth init`.

**Expected Behavior:**

The `geth init` command should complete without any errors, ensuring that the system is correctly initialized.

**Actual Behavior:**

An error stating "Head block is not reachable" is thrown during the initialization process.

**Environment:**
- op-geth version: commit 641e996a2dcf1f81bac9416cb6124f86a69f1de7 
- Operating System: ubuntu 24.04

**Additional Context:**

I suggest investigating the root cause of the "Head block is not reachable" error and determining whether it might affect future operations. After that, modify the `geth init` command of the document.

**Comment by krofax** [comment]
@opfocus We are working on updating this tutorial, for now i'll close this issue, once the tutorial is revamped i'll escalate here, thanks for your patience.
