### ISSUE TITLE
Design X Docs

### ISSUE THREAD

**Issue by sbvegan** [ethereum-optimism/docs#87]
We can coordinate Jason's requests. The primary things atm

- [x] enabling the theme
- [x] working on the index page
- [x] navbar external links
- [x] styling alignment for thumbs up/down widget in TOC

**Comment by jasoncostello** [comment]
I'm going to punt on styling the index page. We don't have solid marketing art styles or assets and the landing page is functional. It'd be better to revisit when the brand design is more finalized. 

Feel free to close this issue. 

I will be sending through one more PR with some tweaks and fixes to spacing, type and dark mode. 

cc/ @pifafu
