### ISSUE TITLE
Creating Your Own L2 Rollup Testnet: Cannot start op-proposer

### ISSUE THREAD

**Issue by bwakabats** [ethereum-optimism/docs#880]
When I run the op-proposer I get the following output:

![image](https://github.com/user-attachments/assets/0288866c-5d95-4b3d-8074-020fb5a85e51)

(I have added 2 info lines to the code so I can see the contract address.)

This is the third time I have run through the whole process and each time it is the wrong contract address.

I am not publishing my own contract and am tying to get the system to talk to the OP Sepolia Testnet contract 0x4e59b44847b379578588920cA78FbF26c0B4956C.

I think the issue is with the .deploy file I am generating, that contains:
"L2OutputOracleProxy": "0x5D94CA1257D8d54bC4e97918E6bFB21510bFCd87"

How do I generate this file to point to the 0x4e59b44847b379578588920cA78FbF26c0B4956C address?

**Comment by krofax** [comment]
@bwakabats I'm going to look into this issue today.

**Comment by bwakabats** [comment]
If I skip this step: 

`forge script scripts/Deploy.s.sol:Deploy --private-key $GS_ADMIN_PRIVATE_KEY --broadcast --rpc-url $L1_RPC_URL --slow
`

Then this step fail...

`go run cmd/main.go genesis l2 (etc)
`

...with "cannot read L1 deployments" because the .deploy files havent been created.

But if I run the forge script step it start to burn lots of ETH gas and runs out eventually, and a completely new address (i.e. not 0x4e59b4....) is written to the .deploy file.

**Comment by krofax** [comment]
@bwakabats We are working on updating this tutorial, for now i'll close this issue, once the tutorial is revamped i'll escalate here, thanks for your patience.

**Comment by bwakabats** [comment]
I have been given details on how to tweak the instruction to work with Berachain, so I am going to pursue that.
