### ISSUE TITLE
Feedback for “Network Upgrades” [Add Bedrock Date?]

### ISSUE THREAD

**Issue by MSilb7** [ethereum-optimism/docs#927]
I was looking for the Bedrock activation date, but noticed that it wasn't listed in the Network Upgrades page: https://docs.optimism.io/builders/node-operators/network-upgrades

**Comment by sbvegan** [comment]
Good idea, it was on June 6th 2023 ([source](https://blog.oplabs.co/reproduce-bedrock-migration/)), but idk where to find the timestamp because its not in the specs.

**Comment by MSilb7** [comment]
From our [old dashboards](https://dune.com/oplabspbc/optimism-bedrock-migration-impact-dashboard), 105235062 was the last pre-migration block on OPM.

First Bedrock block: https://optimistic.etherscan.io/block/105235063
