### ISSUE TITLE
[DOCS] Explain tx finality, fault proof window, and sequencer policy

### ISSUE THREAD

**Issue by zainbacchus** [ethereum-optimism/docs#942]
## Brief Description of the Docs Request
New docs page covering the nuances of tx finality, sequencer policy and challenge periods to debunk the belief that OP Stack chains take 7 days for finalization

## Description of the Documentation You'd Like
See here: https://docs.google.com/document/d/1edsf4eFjLcs5t7xIJ2DEYw1grw2yNz9qbeEOWEfYdaQ/edit

**Comment by krofax** [comment]
Transaction Finality Explainer PR - https://github.com/ethereum-optimism/docs/pull/987
