### ISSUE TITLE
[DOCS] Sentence case all headers

### ISSUE THREAD

**Issue by bradleycamacho** [ethereum-optimism/docs#947]
We recently made [updates to our style guide](https://github.com/ethereum-optimism/docs/pull/945). Most of theses changes won't require updates or sweeps to existing content. The one thing we DO need to sweep for is sentence case headers.

This issue is to track the work of sweeping all headers on the site and making them sentence case.

I've done a few and they aren't too bad. This seems to just bee 1-3 hours of heads down work. 

Currently completing the work in this PR: https://github.com/ethereum-optimism/docs/pull/946

- [x] Train CodeRabbit to follow the documentation style guide

**Comment by sbvegan** [comment]
Completed in: https://github.com/ethereum-optimism/docs/pull/967
